### ISSUE TITLE
Add persistence for games

### ISSUE THREAD

**Issue by ds-jkreutzfeld** [continuous-poker/dealer#3]
Currently, all game information is only stored in memory and is lost on service restart.
To make the dealer more reliable, the data needs to be (optionally) stored in a persistent way.
If the service starts and a persisted game is in running mode, it should be resumed automatically.
Game data needs to be stored frequently to avoid data loss as much as possible.

**Comment by ds-jkreutzfeld** [comment]
Server ran out of memory in the last workshop, so heap space is already an issue. Persisting the game data externally would help with this.

**Comment by jkreutzfeld** [comment]
I implemented a simple form of persistence using a json file. Every 10 seconds, the application will store the current state of all registered games to the file. On startup this file will be read in and the games will be restored (although not started automatically).
This way, we can handle server restarts or updates of the dealer without needing to set up games again.
The location of the file can be configured using the ``persistence.path`` key.
This simple solution does not bring in any infrastructure requirements, which is nice too.
